name: My first pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: uptime
        run: uptime
      - name: Number of processor 
        run: nproc
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echohello


